//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeImp.Fluxtreme.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::CodeImp.Fluxtreme.Configuration.DatasourceSettingsCollection Datasources {
            get {
                return ((global::CodeImp.Fluxtreme.Configuration.DatasourceSettingsCollection)(this["Datasources"]));
            }
            set {
                this["Datasources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public long AutoExpandMaxTableRows {
            get {
                return ((long)(this["AutoExpandMaxTableRows"]));
            }
            set {
                this["AutoExpandMaxTableRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public long AutoExpandMaxTables {
            get {
                return ((long)(this["AutoExpandMaxTables"]));
            }
            set {
                this["AutoExpandMaxTables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public long AutoExpandMaxTotalRows {
            get {
                return ((long)(this["AutoExpandMaxTotalRows"]));
            }
            set {
                this["AutoExpandMaxTotalRows"] = value;
            }
        }
    }
}
